-- ============================================================
-- Seed 21 Business Applications (Generated)
-- Run AFTER create_applications_table.sql
-- ============================================================

INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Mr. Bill’s Pipe & Tobacco Company', 'Donna Brown', 'donna.brown.mr.bills.pipe.tobacc@example.com', '(702) 221-9771', '4441 W Flamingo Rd', 'Las Vegas', 'NV', '89103', 'LIC-NV-2023-5506', '41-4744854', 'https://mr-bills.com', 'wholesaler', 'Vape & Smoke Shop', '$5k-$10k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Still Smoking Vapor & Smoke Shop', 'Emily Williams', 'emily.williams.still.smoking.vapor.@example.com', '(702) 227-3021', '2605 S Decatur Blvd, Suite 107', 'Las Vegas', 'NV', '89102', 'LIC-NV-2025-7912', '14-1499914', 'https://www.stillsmokinglv.com', 'wholesaler', 'Tobacco & Pipe Shop', '$10k-$25k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Smokes Mart', 'Paul Taylor', 'paul.taylor.smokes.mart@example.com', '(702) 510-6468', '9355 W Flamingo Rd', 'Las Vegas', 'NV', '89147', 'LIC-NV-2025-1434', '81-4335942', 'https://smokesmartvegas.com', 'wholesaler', 'Vape Lounge', '$25k-$50k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Las Vegas Paiute Tribal Smoke Shop – Main Street', 'Paul Anderson', 'paul.anderson.las.vegas.paiute.tri@example.com', '(702) 366-1101', '1225 N Main St', 'Las Vegas', 'NV', '89101', 'LIC-NV-2025-5557', '10-3678638', 'https://www.lvpaiutesmokeshop.com/main-street', 'wholesaler', 'Vape Lounge', '$25k-$50k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Snow Mountain Smoke Shop', 'Jennifer Rodriguez', 'jennifer.rodriguez.snow.mountain.smoke.@example.com', '(702) 645-2957', '11525 Nu-Wav Kaiv Blvd', 'Las Vegas', 'NV', '89124', 'LIC-NV-2023-4527', '53-2714803', 'https://www.lvpaiutesmokeshop.com/snowmountain', 'wholesaler', 'Tobacco & Pipe Shop', '$25k-$50k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Gorilla Radio Smoke Shop', 'Richard Lopez', 'richard.lopez.gorilla.radio.smoke.@example.com', '(702) 818-4400', '4225 S Eastern Ave, #5', 'Las Vegas', 'NV', '89119', 'LIC-NV-2024-5333', '15-8707870', 'https://www.gorillaradioonline.com/service/location/', 'wholesaler', 'Head Shop', '$5k-$10k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('HQ Vape & Smoke – Denver', 'Kimberly Williams', 'kimberly.williams.hq.vape.smoke.denver@example.com', '(303) 968-1728', '611 E 13th Ave', 'Denver', 'CO', '80203', 'LIC-CO-2025-5803', '90-7067228', 'https://420hq.com/specials-and-locations/denver-co/', 'wholesaler', 'Head Shop', '$10k-$25k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Purple Haze – Denver', 'William Johnson', 'william.johnson.purple.haze.denver@example.com', '(303) 715-0055', '1951 S Broadway Blvd', 'Denver', 'CO', '80210', 'LIC-CO-2025-4733', '47-2338687', 'https://shoppurplehaze.com/pages/contact-us', 'wholesaler', 'Vape & Smoke Shop', '$5k-$10k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Rusty’s Vape and Smoke Shop – Peoria', 'Kimberly Rodriguez', 'kimberly.rodriguez.rustys.vape.and.smok@example.com', '(303) 307-8789', '4611 Peoria St, Unit A-1', 'Denver', 'CO', '80239', 'LIC-CO-2024-6977', '30-7210606', 'https://rustysvapeandsmokeshop.com/', 'wholesaler', 'Smoke Shop', '$10k-$25k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Rusty’s Vape and Smoke Shop – Quebec', 'Joshua Thompson', 'joshua.thompson.rustys.vape.and.smok@example.com', '(303) 287-4111', '6089 Quebec St, Suite C', 'Commerce City', 'CO', '80022', 'LIC-CO-2025-2169', '87-3871230', 'https://rustysvapeandsmokeshop.com/', 'wholesaler', 'Head Shop', '$10k-$25k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Magnolia Road Smoke & Vape – Boulder', 'Matthew Anderson', 'matthew.anderson.magnolia.road.smoke.@example.com', '(303) 632-7052', '1750 30th St, #86', 'Boulder', 'CO', '80301', 'LIC-CO-2024-5422', '91-4684531', 'https://magnoliaroadcc.com/dispensary-locations/old-boulder-smoke-vape/', 'wholesaler', 'Vape Lounge', '$15k-$30k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Bear Necessities – Greeley', 'David Davis', 'david.davis.bear.necessities.gre@example.com', '(970) 351-0049', '1506 8th Avenue', 'Greeley', 'CO', NULL, 'LIC-CO-2023-6168', '61-5491946', 'https://bearnecessitiessmokeshops.com/', 'wholesaler', 'Tobacco & Pipe Shop', '$10k-$25k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('The Smoking Buddha – Parker', 'Rachel Lewis', 'rachel.lewis.the.smoking.buddha.p@example.com', '(303) 840-4388', '19511 E Parker Square Dr', 'Parker', 'CO', '80134', 'LIC-CO-2025-6155', '37-9375710', 'https://www.smokingbuddhaco.com/', 'wholesaler', 'Tobacco Retailer', '$25k-$50k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('World of Smoke & Vape – Parker', 'Daniel Rodriguez', 'daniel.rodriguez.world.of.smoke.vape.@example.com', '(303) 600-8735', '17002 Mainstreet', 'Parker', 'CO', '80134', 'LIC-CO-2023-5040', '81-5408072', 'https://www.worldofsmokenvape.com/parker/', 'wholesaler', 'Vape Lounge', '$25k-$50k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('710 Pipes – Broomfield', 'Amy Gonzalez', 'amy.gonzalez.710.pipes.broomfield@example.com', '(303) 630-0710', '450 Alter St', 'Broomfield', 'CO', '80020', 'LIC-CO-2024-4593', '27-9548432', 'https://www.710pipes.com/broomfield/', 'wholesaler', 'Tobacco Retailer', '$5k-$10k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Bronco Distribution', 'David Ramirez', 'david.ramirez.bronco.distribution@example.com', '(720) 485-5940', '5763 Logan Ct', 'Denver', 'CO', '80216', 'LIC-CO-2023-3504', '90-3684052', 'https://broncodistribution.com/contact-us/', 'distributor', 'Supply Chain Distribution', '$50k-$100k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Phresh Picks Distribution', 'Kimberly Gonzalez', 'kimberly.gonzalez.phresh.picks.distrib@example.com', '1-833-2-PHRESH / (505) 244-7273', '1301 Cuesta Arriba Ct NE, Suite C', 'Albuquerque', 'NM', '87113', 'LIC-NM-2025-8668', '77-5218028', 'https://www.phreshpicks.com/contact-us', 'distributor', 'Distribution', '$50k-$100k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('MWI (Mike’s Worldwide Inc.)', 'Emily Harris', 'emily.harris.mwi.mikes.worldwide.@example.com', '(713) 771-7912', '10515 Harwin Dr, #136', 'Houston', 'TX', '77036', 'LIC-TX-2024-6573', '24-5924115', 'https://www.gomwi.com/', 'distributor', 'Supply Chain Distribution', '$75k-$150k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('PrimeCo Wholesale', 'Stephanie Smith', 'stephanie.smith.primeco.wholesale@example.com', '(650) 871-5500', '159 W Harris Ave', 'South San Francisco', 'CA', '94080', 'LIC-CA-2025-5315', '74-3997281', 'https://primecowholesale.com/', 'distributor', 'Distribution', '$100k-$250k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('HS Wholesale', 'Donna Taylor', 'donna.taylor.hs.wholesale@example.com', '(630) 882-2222', 'Address not verified from cited source', 'Unknown', 'IL', NULL, 'LIC-XX-2025-4258', '29-7273233', 'https://hswsupply.com/', 'distributor', 'Wholesale Distribution', '$50k-$100k/month', 'pending', NOW());
INSERT INTO applications (business_name, contact_name, email, phone, address, city, state, zip, license_number, ein, website, account_type, business_type, volume_estimate, status, submitted_at) VALUES ('Wisemen Wholesale', 'Angela Hernandez', 'angela.hernandez.wisemen.wholesale@example.com', '(630) 501-1512', '857 Industrial Dr', 'Bensenville', 'IL', '60106', 'LIC-IL-2024-1319', '24-7089806', 'https://wisemenwholesale.com/', 'distributor', 'Regional Distribution', '$75k-$150k/month', 'pending', NOW());